:TITLE
S3DGRADD DSP

:KEY
S3DGRADD

:CONFIG :MODE=PRIMARY
SET C1=S3DGRADD

:WININI :MODE=PRIMARY :MODE=WINDOWS
%WINPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_H
%WINHPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_J
%WINJPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_T
%WINTPATH%\SYSTEM.INI
Desktop IconSpacing 75

