:TITLE
GENGRADD DSP

:KEY
GENGRADD

:CONFIG :MODE=PRIMARY
SET C1=GENGRADD,SBFILTER

:WININI :MODE=PRIMARY :MODE=WINDOWS
%WINPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_H
%WINHPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_J
%WINJPATH%\SYSTEM.INI
Desktop IconSpacing 75

:WININI :MODE=PRIMARY :MODE=WINDOWS_T
%WINTPATH%\SYSTEM.INI
Desktop IconSpacing 75

